### ISSUE TITLE
Speed Issue

### ISSUE THREAD

**Issue by dmitry-saritasa** [kutlugsahin/vue-smooth-dnd#1]
Good job with the component, but on Fedora 27 with Version 65.0.3325.181 (Official Build) (64-bit) the speed is slow (card demo). Very slow, with substantial delay, "jumpy" effects and CPU spikes. 

**CPU jumps to 77%**

see the CPU spike 
![image](https://user-images.githubusercontent.com/1747653/39024110-8ce2b9d8-43f3-11e8-8336-ca11892fd6bf.png)

**Comment by kutlugsahin** [comment]
Hi @dmitry-saritasa, I have tested with chrome firefox edge and ie11 on windows, mac and android and did not see any performance issues even on mobile devices. It's really hard to tell the reason why you are having this issue. may be it is specific to the hardware you run the demo application. So I am closing this issue
