### ISSUE TITLE
Drag preview location

### ISSUE THREAD

**Issue by giancarllorojas** [kutlugsahin/vue-smooth-dnd#100]
First this library is great, I've been using it for a while.

One thing I wanted to do, but didn't found anywhere a way, is when dragging a element to a location that It can be droped, how can I make put a css selector to this place where the element will be droped? Kinda like trello that has a shadow where the element is marked to be droped atm

Thanks in advance!

**Comment by davestewart** [comment]
At least a couple of other issues about this too:

- #15 
- #94

**Comment by kutlugsahin** [comment]
Yes indeed there are similar issues. thanks @davestewart .
Since requests for that rising up, I think I should start planning to add this feature.
I'll ping here when it's done.
Cheers!

**Comment by kutlugsahin** [comment]
Hey @giancarllorojas 
Check out v0.4.0 with the new **drop-placeholder** property.
Cheers!!

**Comment by giancarllorojas** [comment]
That was super quick, thanks very much!

**Comment by davestewart** [comment]
How does one make this work?

**Comment by davestewart** [comment]
Finally figures this out (docs could use some clarification):

```
:drop-placeholder="{ className: '<your class here>' }"
```
