### ISSUE TITLE
@move event

### ISSUE THREAD

**Issue by danieldevsquad** [kutlugsahin/vue-smooth-dnd#101]
Is there an event being fired every time we change the element index **while** the element is being dragged (moved)?

**Comment by davestewart** [comment]
You can add and remove your own using startDrag and endDrag

**Comment by kutlugsahin** [comment]
Also check dropReady which is fired when the index of drop preview changed in container

**Comment by danieldevsquad** [comment]
That is sweet! I need a way to synchronize elements from separate containers and that will help me a lot. Thank you!
