### ISSUE TITLE
import { applyDrag, generateItems } from "./utils"; error module not found

### ISSUE THREAD

**Issue by ilongley** [kutlugsahin/vue-smooth-dnd#11]
I've installed via npm but utils.js is not included in the module.

Any idea where I'm going wrong?

**Comment by ilongley** [comment]
I've fixed the error by importing applyDrag and generateItems from the smooth-dnd module -

import { applyDrag, generateItems } from "smooth-dnd";

**Comment by ilongley** [comment]
But now I get another error - Cannot read property 'wrap' of undefined

**Comment by ilongley** [comment]
If anyone could help me get this library set up properly within a Laravel/Vue environment I'd really appreciate it.

**Comment by TitanFighter** [comment]
Functions inside `./utils.js` are used for demo. In your projects you can\should implement your own functions.

[Example from my project](https://codesandbox.io/s/nwyzv6qv2p), where I do not use `generateItems` (because I provide my own set of data) and where I do not use `applyDrag` in `onDrop`.

**Comment by ilongley** [comment]
@TitanFighter 
Thanks for the reply, I realised that after posting.

I still get an error - Cannot read property 'wrap' of undefined when the library is bootstrapping though - any ideas?

**Comment by kutlugsahin** [comment]
@ilongley 
Do not import applyDrag and generateItems from anywhere like 'smooth-dnd'. They are the local util functions for demo app. But you can copy the functions if you like to your own project. May be that because you are getting the error.

**Comment by robjbrain** [comment]
It would be better if the "Usage" section was a copy and paste-able example, so that people can get started instantly and have a play around?

**Comment by Carlos-Henreis** [comment]
I agree with @robjbrain

**Comment by ilyaDegtyarenko** [comment]
**Guys, look in demo at source.**

![2019-01-12 10 08 20](https://user-images.githubusercontent.com/37239202/51070934-4018b080-1652-11e9-8c2e-8f6a3ede21d7.png)
![2019-01-12 10 09 44](https://user-images.githubusercontent.com/37239202/51070935-4018b080-1652-11e9-9729-5d6fbebd5035.png)
