### ISSUE TITLE
lock element dragging in container

### ISSUE THREAD

**Issue by aosnow** [kutlugsahin/vue-smooth-dnd#112]
excuse me,
how dragging element  in container.

thanks.

**Comment by kutlugsahin** [comment]
see 'lock-axis' property in the [docs](https://github.com/kutlugsahin/vue-smooth-dnd). An you can also set behaviour="contain" if you want to restrict dragged item inside the container.

**Comment by aosnow** [comment]
that's great, thanks a lot
