### ISSUE TITLE
add support for set tag

### ISSUE THREAD

**Issue by philippkuehn** [kutlugsahin/vue-smooth-dnd#12]
It would be nice to set a tag for container and draggable like:

```html
<Container tag="table">
    <Draggable tag="tr>
        ...
    </Draggable>
</Container>
```

**Comment by kutlugsahin** [comment]
Yes its already planned. I just trying to apply a common solution for all three libraries. tag is a good and simple solution for this. I am also considering a render function for root element to render an html element or a component. Ideas appreciated

**Comment by kutlugsahin** [comment]
Basically the same issue with #2
