### ISSUE TITLE
Seems that IE11 is not more supported

### ISSUE THREAD

**Issue by AGachet** [kutlugsahin/vue-smooth-dnd#121]
I've created an app using this awesome lib (thanks for this work), and I just noticed that the current version `"vue-smooth-dnd": "^0.8.0"` doesn't work with IE11. 

I've tested the [demo page](https://kutlugsahin.github.io/vue-smooth-dnd/#/cards) on IE11 which looks not working also...

Vue-smooth-dnd droped IE support? Or it's a mistake? Or it's something else I don't understand?

**Comment by kutlugsahin** [comment]
You should add es6 polyfills to your ie11 application. (i.e Object.assign) Check out [https://github.com/zloirock/core-js](https://github.com/zloirock/core-js)
