### ISSUE TITLE
[Bug] horizontal sortable is not working on Card Board demo page

### ISSUE THREAD

**Issue by ivictbor** [kutlugsahin/vue-smooth-dnd#128]
To reproduce:
1 open demo page
2 try to move column as on gif

![68747470733a2f2f7261776769742e636f6d2f6976696374626f722f7061696e746572726f2f6d61737465722f646f63732f7061696e746572726f5f6769662e676966](https://user-images.githubusercontent.com/1838656/66738480-4bb23580-ee77-11e9-9501-5135dd87ba06.gif)

**Comment by kutlugsahin** [comment]
Should be fixed in version 0.8.1

**Comment by ivictbor** [comment]
Works awesome!
