### ISSUE TITLE
What is actually deployed to demo page?

### ISSUE THREAD

**Issue by ivictbor** [kutlugsahin/vue-smooth-dnd#129]
Hello @kutlugsahin and thanks for awesome work and project! I know you might be a busy on other work, but could I ask a small question: 
Could you please advice which version deployed to your demo? 
When I try run it locally from master I have a bug:

1. Open Page
2. Move Horisontal scroll to the end by dragging scrollbar track
3 try to sort card in last column
4. It thinks that I want to place it to the last column
5. 2nd and next drag after scroll work fine, so probably I could somehow call some kind of refresh as workaround by defining onscroll handler?

![image](https://user-images.githubusercontent.com/1838656/66766237-4aecc400-eeb6-11e9-86d5-ea465e235b8f.png)

There is no this bug when I try it on your demo page, but I have this bug in my project

**Comment by ivictbor** [comment]
@kutlugsahin was fixed in demo by downgrading `smooth-dnd`

```
vue-smooth-dnd-master $ npm i smooth-dnd@0.11.0
```

**Comment by ivictbor** [comment]
on vue-smooth-dnd this was fixed by downgrade to "vue-smooth-dnd": "^0.7.0",

**Comment by kutlugsahin** [comment]
Hey @ivictbor 
This bug is fixed in vue-smooth-dnd 0.8.1 and demo page is also updated to use latest version

**Comment by ivictbor** [comment]
Thanks @kutlugsahin , awesome! I will check it out soon. We use your package for kanban board implementation, great job.

**Comment by ivictbor** [comment]
Works awesome

**Comment by ivictbor** [comment]
Works awesome
