### ISSUE TITLE
Vue-js Nested component draggable

### ISSUE THREAD

**Issue by karabuluthakan** [kutlugsahin/vue-smooth-dnd#13]
Hello!

I have a situation where I have a difficult scenario.
1- There are three separate components, which may be draggable within themselves
2- These three components may also be draggable in a single line

How can I do that?

**Comment by kutlugsahin** [comment]
Nested containers which accept drops from each other is still an issue to improve. But anyway 
check shouldAcceptDrop function to achieve that scenario. see #5
