### ISSUE TITLE
Doesn't work on Chrome 44

### ISSUE THREAD

**Issue by pbelyaev** [kutlugsahin/vue-smooth-dnd#14]
I opened up the Demo page (https://kutlugsahin.github.io/vue-smooth-dnd/) on MacOS High Siera Chrome 44 and it throws a lot of errors in console (see the screenshot below)

![screen shot 2018-06-05 at 4 51 00 pm](https://user-images.githubusercontent.com/6713852/40977005-ce5c1320-68e0-11e8-818d-72c55cb3d927.png)

However the react version of the plugin works fine

![screen shot 2018-06-05 at 4 54 35 pm](https://user-images.githubusercontent.com/6713852/40977142-2ea90120-68e1-11e8-80af-446658e5a140.png)

**Comment by kutlugsahin** [comment]
Its about the demo app. Object.assign added in chrome 45. So I added a polyfill for it. it should be fine now
