### ISSUE TITLE
CDN option?

### ISSUE THREAD

**Issue by elimintz** [kutlugsahin/vue-smooth-dnd#142]
Great looking component. I would like to try using it in my project https://justpy.io to support drag and drop.

Since it is a Python project, I  need the ability to either get it from a CDN or insert a standalone JavaScript file into my templates.

If it is not too much work, either would work for me.

**Comment by davestewart** [comment]
Ta da!

https://www.jsdelivr.com/package/npm/vue-smooth-dnd

**Comment by elimintz** [comment]
Thank you very much!
