### ISSUE TITLE
Example that supports placeholders / gaps / blank spaces in a draggable list

### ISSUE THREAD

**Issue by u01jmg3** [kutlugsahin/vue-smooth-dnd#15]
Basically I'm trying to create something like this rather crude [jQuery UI example](https://jsfiddle.net/ali_soltani/6yo9djcb/1/).

- You can drag any of the words to a free gap in any order
- You can override a word with another (which returns the overridden word back to the pool)
- You can drag an allocated word back to the pool leaving the gap open as it was
- You can remove a word once it is allocated to a gap using the close button

I've looked at the examples, but it seems like they don't allow "blank" items to exist.

Does anyone know of an example that supports this, or have an idea how it can be achieved with this library?

**Comment by TitanFighter** [comment]
> but it seems like they don't allow "blank" items to exist

How about to make "blank" items `display: none` or `visibility: hidden`? So you can use some "blank\default" items as a workaround.

**Comment by u01jmg3** [comment]
Thanks - can you provide a working example/demo?

**Comment by kutlugsahin** [comment]
There is an undocumented value for 'behaviour' property called 'drop-zone'. When set, the container will not sort its elements which you can use it to be containers to drop word to. The rest is pretty straightforward. Simply update the content of the 'word' container as you wish after drop.

**Comment by u01jmg3** [comment]
Any chance of providing a working example? It would be greatly appreciated.

**Comment by u01jmg3** [comment]
Also, is it worth updating the docs?

**Comment by kutlugsahin** [comment]
Check out [https://codesandbox.io/s/mok9x9my6y](https://codesandbox.io/s/mok9x9my6y).
It is not the exact same thing but I hope it will give some idea.
I will update the docs after it is implemented and tested completely. But for your case it works fine.
Cheers!
