### ISSUE TITLE
A way to completely disable dragging ?

### ISSUE THREAD

**Issue by laurent-brisbois** [kutlugsahin/vue-smooth-dnd#182]
Hello everyone.

I'm looking for a way to completely prevent the user from starting dragging any element.
Is there a way to do that ?

I mean maybe I can set the `drop=false` prop (doesn't work for me yet) but the user will still be able to start dragging an element before it is refused by the concerned column..

**Comment by laurent-brisbois** [comment]
Found a way to do it..

I conditionnally set a class for the `drag-handle-selector` prop, based on permissions (in my case).
When it the user doesn't have permission, it doesn't set the appropriate class and my items are no longer draggable.

**Comment by Yihao-G** [comment]
Just comment upon @laurent-brisbois's solution:

Setting `drag-handle-selector` to `undefined` or an empty string doesn't work, because that will make the entire element draggable, according to the docs:
> If not given item can be grabbed from anywhere in its boundaries.

Just set `drag-handle-selector` to a non-existent class to disable dragging.

**Comment by vinchilive** [comment]
another possible solution:
```
<smooth-container
    ....
    @mousedown="onMouseDown"

...

function onMouseDown(event: MouseEvent) {
  if (disabledCondition) {
    event.stopPropagation()
  }
}
```

**Comment by ying-manatal** [comment]
> Just comment upon @laurent-brisbois's solution:
> 
> Setting `drag-handle-selector` to `undefined` or an empty string doesn't work, because that will make the entire element draggable, according to the docs:
> 
> > If not given item can be grabbed from anywhere in its boundaries.
> 
> Just set `drag-handle-selector` to a non-existent class to disable dragging.

Thanks! This worked great for me.

```
<Container :drag-handle-selector="conditionToDisable ? 'drag-disabled' : ''">
```
