### ISSUE TITLE
Library doesn't build to es5?

### ISSUE THREAD

**Issue by ispal** [kutlugsahin/vue-smooth-dnd#19]
Hi, 

I use this awesome library and IE 10 gives error because of the **const** used in build version of this library. Is it possible to build (**dist**) this library to use ES5?

**Comment by kutlugsahin** [comment]
Hi @ispal 
The demo page is not compiled to es5, but the library dist is in es5. But the thing is I never targeted before IE11 and not sure it will work on IE10.

**Comment by ispal** [comment]
Yeah, nevermind. I had another issue
