### ISSUE TITLE
Possibility to render using slots

### ISSUE THREAD

**Issue by ispal** [kutlugsahin/vue-smooth-dnd#2]
Currently the library wraps elements with `div` tags (Draggable & Container). Could this be changed so that it doesn't render any html and gives developer a scoped slot instead. If I understood the code correctly, it's not possibly to use this with table rows?

Simirlarly as here: https://github.com/adamwathan/vue-shopify-sortable-demo

**Comment by ispal** [comment]
I'll see if I have time to help you with this in a form of pull request

**Comment by philippkuehn** [comment]
Would be super nice 🔥

**Comment by kutlugsahin** [comment]
Hello, I have added 'tag' property in 0.2.1. 
See [https://github.com/kutlugsahin/vue-smooth-dnd#tag](https://github.com/kutlugsahin/vue-smooth-dnd#tag)
Hope that helps!
Feedbacks appreciated.

**Comment by peterb-l** [comment]
Excellent library - really neat!  Would be amazing if the Container component could act as a transition-group.  Understandably the tag has to be an html tag:  tag="transition-group" gives "TypeError: n.removeChild is not a function" on render.

**Comment by Davit-000** [comment]
> Excellent library - really neat! Would be amazing if the Container component could act as a transition-group. Understandably the tag has to be an html tag: tag="transition-group" gives "TypeError: n.removeChild is not a function" on render.

same issue, any solutions?
