### ISSUE TITLE
Inline-block layout style dragging possible?

### ISSUE THREAD

**Issue by davestewart** [kutlugsahin/vue-smooth-dnd#23]
I have a new project and am reaching for vue smooth dnd :)

We have a requirement to drag tags from a vertical master list on the left, to any number of horizontal target lists on the right:

![image](https://user-images.githubusercontent.com/132681/43051854-4f064ec2-8e17-11e8-93ca-49e067952d45.png)

Each target would comfortably take, say 10 or so tags, but would then "fill up". As such, we then want to wrap onto the next line, potentially expanding the target area vertically.

I'm not sure if this is even possible right now.

Can you advise?

Thanks.

**Comment by kutlugsahin** [comment]
I don't think this can be solved with current smooth-dnd because it does not support wrapped items. They should be always in one line either vertical or horizontal. That's a feature I want to add in the future though.

**Comment by davestewart** [comment]
I could look at making a PR if you show me whereabouts in the code that's handled?

Would that need to be in the core lib?

**Comment by kutlugsahin** [comment]
Yes it is needed in the core lib smooth-dnd and also requires huge refactor since all calculations are done for one straight axis, it almost means a rewrite for big amount of code base. It is not easy to point a place in the code to refactor unfortunately.

**Comment by davestewart** [comment]
Ah, that's a bugger!

**Comment by davestewart** [comment]
Update: for my use case, I simply added the following CSS to the horizontal drop-zones:

```
display: flex;
flex-wrap: wrap;
```

The static layout works perfectly.

The dragging / over state was less successful, as only the top row moved around as I dragged over, but for this use case, that's acceptable.

**Comment by dhavald99** [comment]
@kutlugsahin : 
HI, it about along time.
any news on this? 
any plan to support in future?

i m waiting for that so.

Thanks

**Comment by davestewart** [comment]
Nope. And this is was in a project I am no-longer involved in, so I can't check - sorry!

**Comment by kutlugsahin** [comment]
Unfortunately, this is not possible with smooth-dnd. All items have to stay on the same line for proper drag.
Closing the issue

**Comment by Sell24** [comment]
> Update: for my use case, **I simply added the following CSS to the horizontal drop-zones**:
> 
> ```
> display: flex;
> flex-wrap: wrap;
> ```
> 
> The static layout works perfectly; items line up in rows then wrap.
> 
> The dragging / over state was less successful, as only the top row moved around as I dragged over, but for this use case, that's acceptable.

Can anyone be kind enough (@davestewart)?  to clarify exactly what this means. I tried putting this css in both the Container, Draggable and every combination but it never seemed to work for me. Any help would be appreciated. I am sure I am missing the obvious. Thanks!

**Comment by davestewart** [comment]
@Sell24 I'm not on this project any more, but it essentially assigning flexbox wrap to the containing div. Target that and you're good.
