### ISSUE TITLE
get mouse release coordinates in drop function

### ISSUE THREAD

**Issue by yehui514** [kutlugsahin/vue-smooth-dnd#24]
I want to put the drag-item with the position where mouse released in container .
How to get mouse release coordinates in drop function?

**Comment by kutlugsahin** [comment]
there is no mouse information in the drop function but I think you can do it adding a mouse up event listener to body in drag-start function and read the value on mouse up and you can remove the listener in either drop or drag-end.

**Comment by yehui514** [comment]
Thank you!
Good idea!
