### ISSUE TITLE
Determine Target onDrop

### ISSUE THREAD

**Issue by jongravois** [kutlugsahin/vue-smooth-dnd#26]
Great package! I am just struggling on finding which container an item is being dragged INTO. So the scenario is to drag from one list to another and post to server the change. HOW do I know which container received the item ... it isn't in the payload nor the props.

Thanks in advance!!!

**Comment by kutlugsahin** [comment]
Hey @jongravois 
Thanks!
Basically it is the container that you set the onDrop function to. You already know target container.

**Comment by jongravois** [comment]
Sorry, I am a little thick and less than fully compentent in Vue.js.

How do I access the Container IN the onDrop function so I can axis it to the server?

So from the groups demo, Container gives me UNDEFINED

<div :style="{'marginLeft': '50px', 'flex': '1'}">
        <Container 
          :group-name="'1'" 
          :get-child-payload="getChildPayload2" 
          @drop="onDrop('items2', $event, Container)">            
          <Draggable v-for="item in items2" :key="item.id">
            <div class="draggable-item">
              {{item.data}}
            </div>
          </Draggable>
        </Container>
      </div>
      <div :style="{'marginLeft': '50px', 'flex': '1'}">
        <Container 
          :group-name="'1'" 
          :get-child-payload="getChildPayload3" 
          @drop="onDrop('items3', $event, Container)">            
          <Draggable v-for="item in items3" :key="item.id">
            <div class="draggable-item">
              {{item.data}}
            </div>
          </Draggable>
        </Container>
      </div>

onDrop: function(collection, dropResult, Container) {
      console.log('ON DROP', collection, dropResult, Container);
      this[collection] = applyDrag(this[collection], dropResult);
    },
