### ISSUE TITLE
Descendant CSS selectors on draggable items

### ISSUE THREAD

**Issue by etune** [kutlugsahin/vue-smooth-dnd#3]
My draggable elements lose formatting while being dragged when I use a descendant CSS selector:

``` css
.card {...} // works

.admin .card {...} // does not work
```

I can't figure out a workaround. Any ideas?

**Comment by etune** [comment]
Oh ok, I see now that the ghost element is at the DOM root. Thanks

**Comment by kutlugsahin** [comment]
I'm glad that it helped :)
