### ISSUE TITLE
Element on drag is way off the cursor position. Any idea why? (img attached)

### ISSUE THREAD

**Issue by JRadagast** [kutlugsahin/vue-smooth-dnd#48]
I haven't a clue why this happens. can anyone help?

    <Container class="novos-campos" drag-handle-selector=".column-drag-handle">
            <Draggable v-for="c in campos">
                <Campos />
            </Draggable>
     </Container>

(the draghandler is being returned by the <Campos /> component.

[Here is the exemple.](https://i.imgur.com/xJLp0H3.gifv)

(edits to fix gif and some other grammar errors)

**Comment by ssnetxyz** [comment]
I have played around with this lib recently, so I'll pitch in. Any padding on `Container`, or any margin on `Draggable` leads to similar effects (offsetting the drag position). I'm sure there are other workarounds, but easiest is to just avoid those (and use wrapping elements with padding/margin instead.)

**Comment by JRadagast** [comment]
> I have played around with this lib recently, so I'll pitch in. Any padding on `Container`, or any margin on `Draggable` leads to similar effects (offsetting the drag position). I'm sure there are other workarounds, but easiest is to just avoid those (and use wrapping elements with padding/margin instead.)

Thanks for the suggestion, i looked into it and that doesn't seem to be the problem i'm having.
I made another gif to illustrate, with a bit of the CSS.
i even tried setting the container and the draggable's padding and margin to 0 and it didn't work.

i'm using display: flex to position the parent of the content on that wizard i've built.

![2018-10-04_08-54-39](https://user-images.githubusercontent.com/7241255/46472470-a9676880-c7b3-11e8-8819-f903308feb59.gif)

**Comment by JRadagast** [comment]
Yes, I do.
I hadn't seen that, thx.

I'll see what I can do to fix this myself.

**Comment by TitanFighter** [comment]
@JRadagast did you find any solution?

**Comment by JRadagast** [comment]
@TitanFighter No, I have to use Transform, so I ended up uninstalling.

**Comment by kutlugsahin** [comment]
Hey all, I have published a workaround in 0.2.6. See #31 
Cheers!
