### ISSUE TITLE
flex wrap support

### ISSUE THREAD

**Issue by SeregPie** [kutlugsahin/vue-smooth-dnd#6]
Hello.
The drag & drop looks nice and smooth. But looks like it does not support wrapped elements. Any plans to implement it in the future?

**Comment by kutlugsahin** [comment]
Hi @SeregPie,
Thanks! Unfortunately there is no support for wrapped elements by design. Honestly, this kind of support will require huge update in the code base so I cannot promise to implement it in the near future.
