### ISSUE TITLE
Restrict the draggable range within the container

### ISSUE THREAD

**Issue by Dzinlife** [kutlugsahin/vue-smooth-dnd#75]
Is there any way to restrict the draggable item within container?

**Comment by P4Thi0ut** [comment]
May be just have access to the js event on the 'event' parameter returned by drag event functions :) so that we can stopPropagation on it ! Thank your for your work !

**Comment by kutlugsahin** [comment]
Hey guys,
For now there is no events to be stopped to propagate but you can use the `drag-handle` property control this behavior. such that, you set the class for the draggables you want to be enabled. Hope this helps

**Comment by kutlugsahin** [comment]
Check out behaviour="contain" in the latest version which will restrict drag within the parent container.
