### ISSUE TITLE
Dragging does not work correctly with new data which are added after initial initialization

### ISSUE THREAD

**Issue by TitanFighter** [kutlugsahin/vue-smooth-dnd#8]
Hi.
First of all thank you for this library and your work.
Unfortunately I have one thing, which does not work.

In your demos and in my code below we have initial data, which works ok from the beginning, but I have a problem when data changes dynamically.

In the demo below there are 2 playlists (one empty - `Electro` and `Slow` - with 3 nested tracks).
I need to copy these 3 tracks to the empty playlist. Once tracks are copied to the empty playlist (`Electro`), there is no smooth 'sliding' effect when you drag any track in this `Electro` playlist and tracks not always change its position, however dragging continues to be ok in the `Slow` playlist.

**Demo\Sandbox**
https://codesandbox.io/s/zqv9m19v8l

I found that the problem is with the first `:key` (for playlists). If replace `:key="playlistObj.playlistTitle"` by `:key="Math.floor(Math.random() * (100 - 1)) + 1"` it starts to work. Any ideas?

Thanks a lot!

**Comment by TitanFighter** [comment]
It was necessary to add
```
<div class="draggable-item">
  ...
</div>
```

**Comment by kutlugsahin** [comment]
Hi @TitanFighter,
It is fixed in v 0.1.6.
You can check it here. I forked your linked and updated the version.
[https://codesandbox.io/s/nwyzv6qv2p](https://codesandbox.io/s/nwyzv6qv2p)
Can you please verify?

**Comment by TitanFighter** [comment]
Thanks a lot! Works perfect!
