### ISSUE TITLE
Change the z-index

### ISSUE THREAD

**Issue by alphatrust-dev** [kutlugsahin/vue-smooth-dnd#80]
When you drag, the smooth-dnd-ghost element has a z-index of 1000 but in my application, I need the z-index to be higher than that.  Can this property be defined or changed?

**Comment by TitanFighter** [comment]
You need to use `:drag-class="your-class` (see [:drag-class](https://github.com/kutlugsahin/vue-smooth-dnd#properties) property) and in your class you can set index you need.

.your-class {
  z-index: 10500;
}

**Comment by alphatrust-dev** [comment]
It seems to style everything except the z-index.  I can give it a drop shadow and change the background color but the z-index stays at 1000 (I think because it's added via a style attribute).

Visual Example
https://i.imgur.com/kRgytgX.png

You can see that the shadow is being applied but the z-index is not.

```
<Container behaviour="copy" group-name="1" :get-child-payload="getStandardChildPayload" drag-class="form-ghost">
    <Draggable v-for="(type, index) in standardTypes" :key="type.id + index">
        <div class="list-group-item">
            <fa-icon icon="grip-vertical" class="drag-handle" /><span class="dragme">drag me <span class="fa fa-arrow-right"></span> </span>{{type.data}}
        </div>
    </Draggable>
</Container>
```
```
.form-ghost {
        transition: .18s ease;
        box-shadow: 1px 1px 5px 2px rgba(0,0,0,.08);
        cursor: grabbing;
        z-index: 5000 !important;
    }
```

**Comment by kutlugsahin** [comment]
Please try to target 'smooth-dnd-ghost' class with !important to set inline z-indez of 1000.
Cheers!

**Comment by alphatrust-dev** [comment]
> Please try to target 'smooth-dnd-ghost' class with !important to set inline z-indez of 1000.
> Cheers!

I already tried that - doesn't seem to work either.

**Comment by kutlugsahin** [comment]
'!important' key has precedence over inline styles so it will overwrite the inline default z-index of 1000.
Make sure your styles are not scoped! I made a demo for you
[https://codesandbox.io/s/yw0qpkqqpz](https://codesandbox.io/s/yw0qpkqqpz)

**Comment by alphatrust-dev** [comment]
> '!important' key has precedence over inline styles so it will overwrite the inline default z-index of 1000.
> Make sure your styles are not scoped! I made a demo for you
> https://codesandbox.io/s/yw0qpkqqpz

I have recreated my situation and targeting the 'smooth-dnd-ghost' class with '!important' doesn't seem to work either.  Here's the example:

https://codesandbox.io/s/rwy7159xnn

**Comment by alphatrust-dev** [comment]
This got resolved in another post: https://github.com/kutlugsahin/vue-smooth-dnd/issues/86
