### ISSUE TITLE
Sortable lists and locked items

### ISSUE THREAD

**Issue by den67rus** [kutlugsahin/vue-smooth-dnd#81]
Is it possible to lock list items in sortable list in a way that those items will stay in that particular place in the list.

For example,

consider this pseudo list with locked items...

- item A
- item B(locked)
- item C(locked)
- item D
- item E
- item F
- item G(locked)

So, I'd like to have the items B,C and G to be fixed in a way that if user drag and drop item D at the start of the list, the item A "jumps" over fixed/locked items B and C with following results...

- item D
- item B(locked)
- item C(locked)
- item A
- item E
- item F
- item G(locked)

https://jsfiddle.net/a17z0pLy/

**Comment by kutlugsahin** [comment]
Hey @den67rus this is not possible at all. All items in the list will move around.

**Comment by den67rus** [comment]
@kutlugsahin why Impossible not? After all example works.
