### ISSUE TITLE
Change the z-index issue (w/ example)

### ISSUE THREAD

**Issue by richcoleman-alphatrust** [kutlugsahin/vue-smooth-dnd#86]
When you drag, the smooth-dnd-ghost element has a z-index of 1000 but in my application, I need the z-index to be higher than that. Can this property be defined or changed?

[I've asked this before](https://github.com/kutlugsahin/vue-smooth-dnd/issues/80) but it got closed out before I could provide [a working example of the issue](https://codesandbox.io/s/rwy7159xnn).  The solutions in the replies didn't help in my scenario.

Issue Example:
https://codesandbox.io/s/rwy7159xnn

**Comment by zerosym** [comment]
The default behavior of smooth-dnd places the ghost element in the same container as the draggable list items, meaning it will be constrained by the container's z-index.

To avoid this you can use :get-ghost-parent option on the container to attach the ghost to a higher level element instead.  For example, the following would work for your sandbox:

    getGhostParent() {
      return document.getElementById('modal')
    }
