### ISSUE TITLE
[FEATURE REQUEST] Ability to constrain dragged item to boundaries

### ISSUE THREAD

**Issue by davestewart** [kutlugsahin/vue-smooth-dnd#89]
I have some tabs I need to reorder. 

It looks really weird to drag them outside of their container!

**Comment by Orimay** [comment]
I do really miss this feature too! Also, this would solve the case where the item moved out of the boundaries and released there, takes it's initial place rather than the last fittable one

**Comment by scriptcoded** [comment]
This would be a wonderful feature to have. It looks rather odd when constraining to an axis and it overflows.

**Comment by scriptcoded** [comment]
The feature doesn't seem to exist in smooth-dnd, though an issue was opened yesterday.

https://github.com/kutlugsahin/smooth-dnd/issues/42

**Comment by kutlugsahin** [comment]
Hey all,
Check out behaviour="contain" property in the latest version. That will only allow dragged item to be floated in the parent Container.
