### ISSUE TITLE
Use in conjunction with transition-group

### ISSUE THREAD

**Issue by zippoxer** [kutlugsahin/vue-smooth-dnd#9]
```javascript
<Container @drop="onDrop">
    <transition-group name="list">
        <Draggable v-for="(conn) in connections" :key="conn.id">
            <h1>{{conn.name}}</h1>
        </Draggable>
    </transition-group>
</Container>
```

That doesn't work. Is it possible to animate enter/leave as well as drag & drop using vue-smooth-dnd?

**Comment by kutlugsahin** [comment]
Hi @zippoxer,
Fist level child of Container must be a Draggable in order to work properly. Try to use transition-group inside Draggable. But if you want this transition for drop effect I would not recommend it since it will not feel very natural.

**Comment by zippoxer** [comment]
@kutlugsahin I want transition-group for enter/leave animations as new items are added/removed from the list. How would putting transition-group inside Draggable help? It seems to me that it won't trigger enter/leave animations.

**Comment by zippoxer** [comment]
@kutlugsahin That works thanks!

**Comment by zippoxer** [comment]
@kutlugsahin This doesn't work as well. Entrance and leave animations don't trigger.

**Comment by junlinguo11** [comment]
@kutlugsahin this problem still exist, any solution?
