### ISSUE TITLE
Disable drag&drop when popping up a modal dialog

### ISSUE THREAD

**Issue by heriisei** [kutlugsahin/vue-smooth-dnd#92]
Hello,

My case is, I have list of dragable cards, each of those cards have button that will popping-up a modal dialog. The problem is, when a modal (that opened from button on the card) popped up, the cards (**that triggered the modal**) can be dragged in background.

This problem does not come if the modal dialog not triggered from the button on dragable card.

So, is there any configuration that can be applied to disable the drag & drop? in my case, disabled the drag & drop in the background when popping up a modal dialog.

Thank you!

**Comment by davestewart** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events

**Comment by kutlugsahin** [comment]
Hey @heriisei this should be fixed in the latest version. Can you please confirm?

**Comment by heriisei** [comment]
@davestewart @kutlugsahin Hey thank you guys for the response, how silly I am, this problem can be solved easily with set the non-drag-area-selector=".modaldialogclass". Because every modal need to inherit the key index from parent <Draggable> directly. This problem is fixed now.

**Comment by barrard** [comment]
Im having trouble getting this non-drag-area-selector to work.

I have a list of drag-able things and each one may conditionally render a slider.
But this code below results in a fully drag-able item :( 
Am I using this correctly?
```javascript
<Draggable class="no-drag" :non-drag-area-selector="'.no-drag'">
    <div >
        Hello
    </div>
    <div>
        <div>
            <input class="no-drag" type="button" value="Save" @click="setHours">
        </div>
    </div>
</Draggable>
```
Thanks for your help
