### ISSUE TITLE
drop Placeholder

### ISSUE THREAD

**Issue by smokezp** [kutlugsahin/vue-smooth-dnd#94]
Is it possible to create something like placeholder area where item will drop?

**Comment by chanlito** [comment]
+1

**Comment by kftzzu** [comment]
+1

**Comment by mustkeom** [comment]
+1

**Comment by LeeHyungGeun** [comment]
+1

**Comment by kutlugsahin** [comment]
Hey @smokezp @chanlito 
Check out v0.4.0 with the new **drop-placeholder** property.
Cheers!!

**Comment by davestewart** [comment]
The man is on 🔥 !
