### ISSUE TITLE
[FEATURE REQUEST] Ability to add containers and draggables dynamically

### ISSUE THREAD

**Issue by davestewart** [kutlugsahin/vue-smooth-dnd#95]
I have a situation where I want to be able to drag a dragged item onto a bin, which will dynamically load content from the server, then I want to the currently-dragged item to be dropped among these objects. 

Right now, it seems that VSDND doesn't support this.

Is this possible now, or would this be difficult to implement?

Regarding workarounds, due to the possible amount of items being loaded from the server, I don't think it would be possible to pre-render.

I'm happy to dig in and see if there could be a possible PR on the base library. 

Can you advise?

Thanks.

**Comment by davestewart** [comment]
So as a workaround, I've tried rendering one `Container` then dynamically changing its `Draggable`s, but this doesn't work.

If you start with 5 items then swap to 10, only the first 5 are interactive.

**Comment by kutlugsahin** [comment]
This will be implemented in core lib. please refer to [https://github.com/kutlugsahin/smooth-dnd/issues/38](https://github.com/kutlugsahin/smooth-dnd/issues/38).

**Comment by kutlugsahin** [comment]
Now Containers can be mounted or unmounted during drag.

**Comment by davestewart** [comment]
Wonderful!
