### ISSUE TITLE
demos: cards: dragging columns stopped working

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [kutlugsahin/vue-smooth-dnd#99]
Checking out master and running the current npm version does not allow dropping columns around. The demo that is on gh-pages does though. Possible regression?

**Comment by davestewart** [comment]
Good catch.

This has been fixed in the latest build of smooth-dnd, but looks like the demo isn't pulling the latest version in.

To fix for now:

```
# in the main repo
npm i
npm run build
cd demo
npm i
npm run dev
```

**Comment by kutlugsahin** [comment]
Thanks @davestewart for replying. That was a temporary problem which should be fix by now.
